name: wear
description: A plugin that offers Flutter support for Wear OS by Google
version: 2.0.0
homepage: https://github.com/timmaffett/flutter_wear_plugin

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"
  flutter: ">=3.9.0-17.0.pre"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mjohnsullivan.flutterwear.wear
        pluginClass: WearPlugin
